Add mod downloader + improve codebase abstraction + add concurrency to operations
notcake/glua-minecraft-tools pull request #1
Opened 2018-11-01 04:17 UTC by SwadicalRag

2018-11-01 18:31 UTC, notcake requested changes

2018-11-01 18:31 UTC, notcake commented on update-mods-md.ts
> +	for(let i=0; i < newLines.length;i++)
The whitespace makes me sad >:

2018-11-02 00:36 UTC, notcake approved these changes

2018-11-02 00:36 UTC, notcake commented on update-mods-md.ts
> +	const newLines: (string | [number,string[][],number[]])[] = [];
whitespace

2018-11-02 00:36 UTC, notcake commented on update-mods-md.ts
> +		updateModIDs(concurrency,table);
whitespace

2018-11-02 00:37 UTC, merged

2018-11-02 00:44 UTC, SwadicalRag commented
im so sorry q_q